### ISSUE TITLE
Cluttered error message on export fail

### ISSUE THREAD

**Issue by itowlson** [deislabs/duffle#823] opened 2019-08-05 23:52 UTC
Tried to export a full bundle and got the following error:

`Error preparing artifacts: UNAUTHORIZED: authentication required; [map[Type:repository Class: Name:deislabs/arsebiscuits-cnab Action:pull]]`

Ignoring for now that I had this image locally so I'm not sure why it's trying to pull it - the formatting with all the Go map stringising spew is cluttered.  Could it say something like `authentication required to pull repository deislabs/cnab-arsebiscuits`?

**Comment by glyn** [comment] 2019-08-06 04:02
The reason the pull is occurring is that the library that `duffle export` is using to grab images reads directly from the remote repository rather than from any docker daemon. The library was designed to run in environments that don't have a docker daemon, such as inside a kubernetes cluster.

The error message is cluttered because `duffle export` simply wraps the error from the underlying library (probably `UNAUTHORIZED: ...`).

Solutions include replacing the underlying library and changing the underlying library to check the docker daemon first and/or to emit a less "cluttered" error message.

**Comment by itowlson** [comment] 2019-08-06 04:04
If it's a string coming from an underlying library then there's not much Duffle can do about it, but if you point me at the underlying library then I will cheerfully raise a bug against that!

**Comment by glyn** [comment] 2019-08-06 04:23
The underlying library is github.com/pivotal/image-relocation which is based heavily on github.com/google/go-containerregistry (a.k.a. GGCR). The error message comes from the latter library. 

The rationale for using github.com/pivotal/image-relocation to implement `duffle export` was in order to write an OCI image layout and my lack of familiarity with other libraries that might do the same. (I helped to implement the OCI image layout support in GGCR, although any evidence of this was accidentally stripped out.)

github.com/pivotal/image-relocation avoids any dependency on the docker daemon so that it can run in environments lacking a daemon, such as inside a kubernetes cluster, although I don't think that is a requirement of `duffle`.

**Comment by jeremyrickard** [comment] 2019-08-12 16:12
Thanks for opening the issue @itowlson. Since you've opened the issue to fix this in pivotal/image-relocation, I'm going to close this.

**Closed by jeremyrickard** 2019-08-12 16:12 UTC
