### ISSUE TITLE
validate input for `duffle build`

### ISSUE THREAD

**Issue by bacongobbler** [deislabs/duffle#527] opened 2018-11-28 00:38 UTC
As we have changed the fields on duffle.toml mulitple times during the PoC, we have a lot of TOML files that are invalid input to `duffle build`, but `duffle build` will still silently accept that input without validation, ending up in weird scenarios like this one:

duffle.toml:

```toml
name = "wordpress"
registry = "cnab"
components = ["cnab"]
version = "0.2.0"
```

```console
$ duffle build .
==> Successfully built bundle wordpress:
```

Instead, `duffle build` should fail when it doesn't find fields that are required from duffle.toml.

**Comment by radu-matei** [comment] 2019-02-08 21:55
This is indeed a duplicate of #363. 

Closing.

**Closed by radu-matei** 2019-02-08 21:55 UTC
Labels: bug
